const questions = {
    en: {
        family: [
            "What is your favorite memory of us as a family?",
            "How did your parents handle conflict when you were a child?",
            "What is one rule your parents had that you will never enforce?",
            "Who was your 'safe person' growing up?",
            "What is a family tradition you want to keep forever?",
            "Do you feel you can be your true self around your relatives?",
            "What is the biggest sacrifice your parents made for you?",
            "How does our family express affection?",
            "What is a generational cycle you want to break?",
            "What is one thing you wish your parents understood about you?",
            "What was the happiest year of your childhood?",
            "Did you feel heard when you were younger?",
            "What is the most valuable lesson a family member taught you?",
            "How has your relationship with your siblings changed over time?",
            "What is a funny story our family always tells?",
            "If you could apologize to a family member, who would it be?",
            "What pressure did you feel from family expectations?",
            "How do you handle family gatherings? Do they drain or recharge you?",
            "What specific meal reminds you of home?",
            "Who holds the family together during tough times?",
            "What does 'home' mean to you?",
            "Have you ever felt like the 'black sheep' of the family?",
            "What is one thing you admire about your father?",
            "What is one thing you admire about your mother?",
            "How did your family celebrate your achievements?",
            "What was your favorite toy growing up?",
            "Did you grow up with too much structure or too little?",
            "What is a secret you kept from your parents?",
            "How do you want to be remembered by your future grandchildren?",
            "What family trait are you most proud of?",
            "What family trait are you afraid of inheriting?",
            "How did your family deal with money growing up?",
            "Did you feel compared to others as a child?",
            "What is the best advice a grandparent gave you?",
            "If you could relive one day from your childhood, which one?",
            "What makes you feel protected?",
            "How do you handle it when a family member disappoints you?",
            "What is the most forgiving thing a family member has done for you?",
            "Do you think you are similar to your parents?",
            "What is a topic your family avoids talking about?",
            "How important is blood relation to you vs. chosen family?",
            "What was your role in the family dynamic (the peacemaker, the rebel, etc.)?",
            "What scared you the most as a child?",
            "How did your family handle grief?",
            "What song reminds you of your childhood?",
            "Who in the family makes you laugh the most?",
            "What is a misunderstanding you want to clear up with your family?",
            "Do you want a family like the one you grew up in?",
            "What is the hardest thing about being a [son/daughter]?",
            "How do you set boundaries with family?",
            "What is your favorite holiday tradition?",
            "If you could ask your ancestors one question, what would it be?",
            "What childhood friend did your family love?",
            "How do you show gratitude to your parents?",
            "What is the biggest lie you told your parents?",
            "When did you realize your parents were just human beings?",
            "What comfort food do you crave when you are sick?",
            "Who in the family do you trust with your life?",
            "What does a 'perfect family' look like to you?",
            "What do you need from your family right now?"
        ],
        goals: [
            "What is the one dream you are afraid to say out loud?",
            "Do you work for passion or for stability?",
            "What does 'success' actually look like to you?",
            "If you knew you couldn't fail, what would you start today?",
            "What is a habit that is holding you back?",
            "Who is your career role model?",
            "Are you living your dream or someone else's?",
            "What motivates you more: praise or accomplishment?",
            "Where do you want to be in 5 years?",
            "What is a skill you wish you learned earlier?",
            "How do you handle burnout?",
            "What is the biggest risk you have taken for your career?",
            "If money didn't exist, how would you spend your time?",
            "What is a goal you gave up on?",
            "What is your definition of a 'rich life'?",
            "Do you prefer working alone or in a team?",
            "What legacy do you want to leave behind?",
            "What is the hardest feedback you ever received?",
            "How do you celebrate small wins?",
            "What are you willing to sacrifice for your goals?",
            "What are you NOT willing to sacrifice?",
            "How do you deal with Imposter Syndrome?",
            "What is a book that changed your mindset?",
            "Do you think you are ambitious?",
            "What is your biggest distraction?",
            "If you could master one talent instantly, what would it be?",
            "What is the best financial decision you ever made?",
            "What keeps you up at night regarding your future?",
            "Do you believe in 'hustle culture' or work-life balance?",
            "What is a project you started but never finished?",
            "How do you handle rejection?",
            "What is your 'Why'?",
            "Who believes in your dreams more than you do?",
            "What is the most stressful part of your week?",
            "If you could start your own business, what would it be?",
            "What brings you into a 'flow state'?",
            "Are you a planner or do you wing it?",
            "What is a goal you achieved that felt empty?",
            "What is a failure that actually helped you?",
            "How do you measure your own growth?",
            "What advice would you give your younger self about money?",
            "Do you think you are reaching your potential?",
            "What environment makes you most productive?",
            "Who do you need to network with?",
            "What is one thing you need to delegate or stop doing?",
            "How do you recharge your creative energy?",
            "What is your retirement dream?",
            "Do you prioritize time or money?",
            "What is the biggest obstacle in your way right now?",
            "How do you stay disciplined when motivation fades?",
            "What is a compliment about your work that meant a lot?",
            "Do you want to be famous or respected?",
            "What is a goal you are working on secretly?",
            "How do you define 'freedom'?",
            "What makes you feel powerful?",
            "If you lost everything today, how would you rebuild?",
            "What is your philosophy on leadership?",
            "Are you afraid of success?",
            "What is the next big step you need to take?",
            "What are you grateful for in your career?"
        ],
        relationship: [
            "What is your primary Love Language?",
            "How do you behave when you are angry?",
            "What is an instant deal-breaker for you?",
            "Do you believe in 'right person, wrong time'?",
            "What is your biggest fear in a relationship?",
            "How do you define 'cheating'?",
            "Do you need a lot of reassurance?",
            "What does emotional safety feel like to you?",
            "Are you friends with any of your exes?",
            "What is the best relationship advice you ever received?",
            "How much alone time do you need?",
            "What is a non-negotiable value for a partner?",
            "Do you believe in soulmates?",
            "How do you handle jealousy?",
            "What is the most romantic thing someone has done for you?",
            "Do you communicate your needs clearly?",
            "What is a toxic trait you are working on?",
            "How important is physical intimacy to you?",
            "Can you forgive infidelity?",
            "What is your attachment style (Secure, Anxious, Avoidant)?",
            "Who was your first heartbreak?",
            "What do you bring to the table in a relationship?",
            "Do you prefer a partner who is similar or opposite to you?",
            "How do you apologize?",
            "What makes you feel most loved?",
            "What is a small gesture that melts your heart?",
            "How do you handle financial disagreements?",
            "Do you want children?",
            "What is the biggest lesson you learned from your last relationship?",
            "Are you a good listener?",
            "What is something you are sensitive about?",
            "How do you show support when your partner is stressed?",
            "Do you believe love is a feeling or a choice?",
            "What is your favorite way to be touched?",
            "How long does it take for you to trust someone?",
            "What is a misconception people have about you in dating?",
            "Do you fall in love fast or slow?",
            "What does a 'healthy argument' look like?",
            "Would you relocate for love?",
            "How important is your partner's relationship with their family?",
            "What is your idea of a perfect date?",
            "Do you hold grudges?",
            "What is one thing you wish you could change about your love life?",
            "How do you handle silence with a partner?",
            "Do you prefer big gestures or consistency?",
            "What makes you feel insecure?",
            "How do you maintain your identity in a relationship?",
            "What is the role of social media in your relationship?",
            "Do you believe in second chances?",
            "What is the deepest connection you have ever felt?",
            "How do you handle it when your partner cries?",
            "What are your thoughts on marriage?",
            "Do you compare your relationship to others?",
            "What is something you need to be forgiven for?",
            "How do you express vulnerability?",
            "What is the sexiest quality in a person?",
            "When do you feel most understood?",
            "What is a secret you have never told a partner?",
            "How do you know when it's time to let go?",
            "What does 'commitment' mean to you?"
        ]
    },
    tl: {
        family: [
            "Ano ang paborito mong alaala kasama ang pamilya?",
            "Paano nag-aaway ang parents mo noong bata ka?",
            "Anong patakaran sa bahay niyo ang hinding-hindi mo gagawin sa anak mo?",
            "Sino ang takbuhan mo noong bata ka pa?",
            "Anong family tradition ang gusto mong ipagpatuloy?",
            "Nagiging totoo ka ba pag kasama mo ang mga kamag-anak mo?",
            "Ano ang pinakamalaking sakripisyo ng magulang mo para sayo?",
            "Paano kayo magpakita ng lambing sa pamilya?",
            "Anong cycle o ugali ng pamilya ang gusto mong putulin?",
            "Ano ang isang bagay na sana naiintindihan ng magulang mo sayo?",
            "Kailan ang pinakamasayang taon ng kabataan mo?",
            "Pakiramdam mo ba pinapakinggan ka noong bata ka?",
            "Ano ang pinaka-importanteng aral na natutunan mo sa pamilya?",
            "Paano nagbago ang samahan niyo ng mga kapatid mo?",
            "Ano ang nakakatawang kwento na laging kinukwento ng pamilya?",
            "Kung pwede kang mag-sorry sa kapamilya, kanino at bakit?",
            "Anong pressure ang naramdaman mo mula sa pamilya?",
            "Nakaka-drain ba o nakaka-recharge ang family gatherings?",
            "Anong ulam ang nagpapaalala sayo ng bahay?",
            "Sino ang taga-ayos ng gulo sa pamilya?",
            "Ano ang ibig sabihin ng 'tahanan' para sayo?",
            "Naramdaman mo na bang ikaw ang 'black sheep' sa inyo?",
            "Ano ang hinahangaan mo sa Tatay mo?",
            "Ano ang hinahangaan mo sa Nanay mo?",
            "Paano sine-celebrate ng pamilya ang tagumpay mo?",
            "Ano ang paborito mong laruan noong bata ka?",
            "Lumaki ka ba na mahigpit ang magulang o maluwag?",
            "Anong sikreto ang tinago mo sa parents mo?",
            "Paano mo gustong maalala ka ng magiging apo mo?",
            "Anong katangian ng pamilya mo ang proud ka?",
            "Anong katangian ng pamilya mo ang ayaw mong manahin?",
            "Paano ang hawak ng pera sa pamilya niyo noong bata ka?",
            "Kinukumpara ka ba sa iba noong bata ka?",
            "Ano ang payo ng Lolo o Lola mo na di mo malilimutan?",
            "Kung mauulit mo ang isang araw noong bata ka, kailan yun?",
            "Ano ang nagpaparamdam sayo na ligtas ka?",
            "Paano mo hinaharap pag nadidisappoint ka sa pamilya?",
            "Ano ang pinaka-forgiving na ginawa ng pamilya mo sayo?",
            "Sa tingin mo, katulad ka ba ng parents mo?",
            "Anong topic ang iniiwasang pag-usapan sa pamilya?",
            "Gaano ka-importante ang kadugo vs. piniling pamilya?",
            "Ano ang role mo sa pamilya (taga-awat, pasaway, etc.)?",
            "Saan ka pinaka-takot noong bata ka?",
            "Paano hinaharap ng pamilya niyo ang pagkawala ng mahal sa buhay?",
            "Anong kanta ang nagpapaalala ng kabataan mo?",
            "Sino ang pinaka-komedyante sa pamilya?",
            "Anong misunderstanding ang gusto mong linawin sa pamilya?",
            "Gusto mo ba ng pamilya na katulad ng kinalakihan mo?",
            "Ano ang pinakamahirap sa pagiging anak?",
            "Paano ka nagse-set ng boundaries sa pamilya?",
            "Ano ang paborito mong ganap pag Pasko o New Year?",
            "Kung makakausap mo ang ninuno mo, anong itatanong mo?",
            "Sinong kababata mo ang gustong-gusto ng pamilya mo?",
            "Paano mo pinapakita ang utang na loob o pasasalamat sa magulang?",
            "Ano ang pinakamalaking kasinungalingan na sinabi mo sa parents mo?",
            "Kailan mo na-realize na tao lang din ang parents mo at nagkakamali?",
            "Anong comfort food ang gusto mo pag may sakit ka?",
            "Sino sa pamilya ang pagkakatiwalaan mo ng buhay mo?",
            "Ano ang itsura ng 'perpektong pamilya' para sayo?",
            "Ano ang kailangan mo mula sa pamilya mo ngayon?"
        ],
        goals: [
            "Ano ang pangarap na takot kang sabihin ng malakas?",
            "Nagta-trabaho ka ba para sa passion o para sa pera?",
            "Ano ang itsura ng 'tagumpay' para sayo?",
            "Kung alam mong di ka mabibigo, anong sisimulan mo ngayon?",
            "Anong habit o bisyo ang pumipigil sayo?",
            "Sino ang career idol mo?",
            "Buhay mo ba ang binubuhay mo o pangarap ng iba?",
            "Ano mas gusto mo: puri o achievements?",
            "Saan mo nakikita ang sarili mo 5 years from now?",
            "Anong skill ang sana natutunan mo noon pa?",
            "Paano mo hinaharap ang burnout o pagod?",
            "Ano ang pinakamalaking risk na ginawa mo sa career mo?",
            "Kung walang pera sa mundo, paano mo gagamitin ang oras mo?",
            "Anong pangarap ang sinukuan mo na?",
            "Ano ang definition mo ng 'mayaman'?",
            "Mas gusto mo bang magtrabaho mag-isa o may ka-team?",
            "Anong legacy o pamana ang gusto mong iwan?",
            "Ano ang pinaka-masakit na feedback na natanggap mo?",
            "Paano mo cine-celebrate ang maliliit na panalo?",
            "Ano ang kaya mong isakripisyo para sa pangarap?",
            "Ano ang HINDI mo kayang isakripisyo?",
            "Paano mo nilalabanan ang pagdududa sa sarili?",
            "Anong libro o movie ang nagbago ng pananaw mo?",
            "Sa tingin mo ba ambisyoso ka?",
            "Ano ang pinaka-nakaka-distract sayo?",
            "Kung pwede kang maging expert sa isang bagay agad, ano yun?",
            "Ano ang pinakamagandang desisyon mo sa pera?",
            "Ano ang iniisip mo sa gabi tungkol sa future mo?",
            "Naniniwala ka ba sa 'hustle culture' o work-life balance?",
            "Anong project ang sinimulan mo pero di mo tinapos?",
            "Paano mo tinatanggap ang rejection?",
            "Ano ang 'Bakit' o rason mo sa ginagawa mo?",
            "Sino ang mas naniniwala sayo kaysa sa sarili mo?",
            "Ano ang pinaka-nakaka-stress na parte ng linggo mo?",
            "Kung magnenegosyo ka, ano ito?",
            "Ano ang ginagawa mo na nawawala ka sa sarili sa sobrang focus?",
            "Planner ka ba o bahala na?",
            "Anong goal ang naabot mo pero parang kulang pa rin?",
            "Anong pagkakamali ang nakatulong sayo?",
            "Paano mo sinusukat ang paglago mo?",
            "Anong payo sa pera ang ibibigay mo sa younger self mo?",
            "Sa tingin mo ba naabot mo na ang potential mo?",
            "Saang lugar ka pinaka-productive?",
            "Sino ang kailangan mong makilala o maging connection?",
            "Ano ang dapat mong ipagawa sa iba o itigil na gawin?",
            "Paano mo binabalik ang creative energy mo?",
            "Ano ang dream retirement mo?",
            "Alin ang priority mo: oras o pera?",
            "Ano ang pinakamalaking harang sa dinadaanan mo ngayon?",
            "Paano ka nagiging disiplinado pag tinatamad ka?",
            "Anong compliment sa trabaho ang tumatak sayo?",
            "Gusto mo bang sumikat o irespeto?",
            "Anong goal ang tinatrabaho mo nang palihim?",
            "Ano ang ibig sabihin ng 'kalayaan' para sayo?",
            "Kailan mo nararamdaman na makapangyarihan ka?",
            "Kung mawala lahat sayo ngayon, paano ka magsisimula ulit?",
            "Ano ang paniniwala mo sa pagiging leader?",
            "Takot ka ba maging successful?",
            "Ano ang susunod na malaking hakbang na dapat mong gawin?",
            "Saan ka nagpapasalamat sa career mo ngayon?"
        ],
        relationship: [
            "Ano ang Love Language mo?",
            "Paano ka magalit sa partner?",
            "Ano ang ugali na hinding-hindi mo matatanggap (deal-breaker)?",
            "Naniniwala ka ba sa 'right person, wrong time'?",
            "Ano ang pinakakinakatakutan mo sa isang relasyon?",
            "Para sayo, ano ang considered na 'cheating'?",
            "Kailangan mo ba lagi ng reassurance o lambing?",
            "Ano ang pakiramdam ng 'safe' sa isang tao?",
            "Kaibigan mo pa ba ang mga ex mo?",
            "Ano ang pinakamagandang payo sa pag-ibig na nakuha mo?",
            "Gaano kadalas mo kailangan mapag-isa?",
            "Anong values ang hindi pwedeng mawala sa partner mo?",
            "Naniniwala ka ba sa soulmates?",
            "Paano ka magselos?",
            "Ano ang pinaka-sweet na ginawa ng tao para sayo?",
            "Nasasabi mo ba ng diretso ang mga kailangan mo?",
            "Anong toxic trait mo ang inaayos mo ngayon?",
            "Gaano ka-importante ang physical intimacy sayo?",
            "Mapapatawad mo ba ang panloloko?",
            "Ano ang attachment style mo (Secure, Anxious, Avoidant)?",
            "Sino ang unang nanakit ng puso mo?",
            "Ano ang ambag mo sa isang relasyon?",
            "Mas gusto mo ba ng partner na katulad mo o kabaligtaran mo?",
            "Paano ka mag-sorry?",
            "Kailan mo nararamdaman na mahal na mahal ka?",
            "Anong maliit na bagay ang nagpapakilig sayo?",
            "Paano niyo aayusin pag may problema sa pera?",
            "Gusto mo ba ng anak?",
            "Ano ang natutunan mo sa huli mong relasyon?",
            "Magaling ka bang makinig?",
            "Saan ka nagiging sensitive o tampuhin?",
            "Paano mo pinapasaya ang partner mo pag stressed siya?",
            "Ang pag-ibig ba ay nararamdaman o pinipili?",
            "Ano ang paborito mong way ng holding hands o yakap?",
            "Gaano katagal bago mo pagkatiwalaan ang tao?",
            "Ano ang maling akala ng mga tao sayo pag dating sa dating?",
            "Mabilis ka bang ma-in love o mabagal?",
            "Ano ang itsura ng 'healthy na away'?",
            "Lilipat ka ba ng tirahan para sa pag-ibig?",
            "Gaano ka-importante ang samahan ng partner mo at pamilya niya?",
            "Ano ang ideal date para sayo?",
            "Nagta-tanim ka ba ng sama ng loob?",
            "Ano ang gusto mong baguhin sa love life mo?",
            "Paano mo hinaharap ang katahimikan kasama ang partner?",
            "Gusto mo ba ng grand gestures o consistency?",
            "Ano ang nagpapababa ng self-confidence mo sa relationship?",
            "Paano mo napapanatili ang sarili mo sa loob ng relasyon?",
            "Ano ang role ng social media sa relasyon niyo?",
            "Naniniwala ka ba sa second chances?",
            "Kailan mo naramdaman ang pinaka-malalim na connection?",
            "Ano ang ginagawa mo pag umiiyak ang partner mo?",
            "Ano ang pananaw mo sa kasal?",
            "Kinukumpara mo ba ang relationship niyo sa iba?",
            "Ano ang kailangan mong ihingi ng tawad?",
            "Paano ka nagpapakita na nasasaktan ka (vulnerability)?",
            "Ano ang pinaka-sexy na ugali ng isang tao?",
            "Kailan mo nararamdaman na naiintindihan ka?",
            "Anong sikreto ang hindi mo pa nasasabi sa partner?",
            "Paano mo malalaman kung kailangan nang bumitaw?",
            "Ano ang ibig sabihin ng 'commitment' sayo?"
        ]
    }
};